### ISSUE TITLE
Create a seed script

### ISSUE THREAD

**Issue by shippy** [YaleSTC/shifts#325]
Out-of-the-box Shifts is useless and hard to test. We should create a basic seed script that will populate the database with a location and users with multiple roles.

**Comment by orenyk** [comment]
The anonymized DB no longer works due to missing migrations (e.g. importing it then running `rake db:migrate` fails), so getting a working seed script running would go a long way towards making this project developer-friendly. @squidgetx recently overhauled the seed script for Reservations (see [here](https://github.com/YaleSTC/reservations/pull/1079)), so perhaps it could serve as the basis for something similar for Shifts?

**Comment by shippy** [comment]
On the topic of seeding with factories: [FactoryGirl authors are against it](http://robots.thoughtbot.com/factory_girl-for-seed-data), but I think their reasons are letting perfect be the enemy of good. On the whole, I think we should do it.

It should be as easy as [this](http://davidmles.com/blog/2014/05/23/seeding-your-database-with-factorygirl-and-faker/). Of course, knowing Shifts' complicated db structure, it's going to be slightly more complicated than that, but we already run a minimal functional setup in testing, so this shouldn't be all that hard.

**Comment by njlxyaoxinwei** [comment]
Note that the seed script should create instances of all different models. As of now the factories in `spec` only cover a small fraction of them. As we write more factories the inter-dependencies and relations will be more complicated. 

I would suggest that instead of writing the entire seed script now, we can use the existing factories to produce a (more than minimal) seed script for Shifts. As our integration test suite covers more and more models, more factories will be written and we can update/enhance our seed.rb accordingly.

**Comment by mnquintana** [comment]
IMO, you shouldn't waste time worrying about having a technically perfect seed script. The seed script is meant to quickly bootstrap the application for developers, not be a user-facing feature, and it's really needed now, not in the future whenever the test suite's done. However, you do need to bootstrap the whole application, so using the few factories you have now doesn't seem sufficient. However you build the seed script, it should be whatever's fastest – Shifts needed a seed script as of 3 years ago.

**Comment by orenyk** [comment]
I'd agree w/ @mnquintana, if we're going to be putting in serious development effort on this project, the ability to set up a clean DB will be pretty critical. I use `rake db:reset` all the time, both during development as well as during code review. I'm not familiar enough with the full functionality of the app to know how many different object types will need to be created, but if you could come up with some minimal set to either implement factories for or to write seed methods for, that would be awesome.

**Comment by njlxyaoxinwei** [comment]
Here are the models that need to be created in the seed script, to track progress:

- [ ] Annoucement
- [x] AppConfig
- [ ] Calendar (department default created along with department)
- [ ] Category (3 built-in ones created along with department)
- [ ] DataEntry
- [ ] DataField
- [ ] DataObject
- [ ] DataType
- [x] Department
- [x] DepartmentConfig (default created along with department)
- [x] DepartmentsUser (created by `user.departments = [@department]`)
- [ ] Email
- [ ] Link < Notice
- [x] LocGroup
- [x] Location
- [ ] LocationsRequestedShift
- [ ] LocationsShiftPreference
- [ ] Notice (abstract interface for Link, Sticky, Announcement)
- [ ] Payform
- [ ] PayformItem
- [ ] PayformItemSet
- [x] Permission (created along with department and loc_group)
- [ ] PunchClock
- [ ] PunchClockSet
- [ ] RepeatingEvent
- [ ] Report
- [ ] ReportItem
- [ ] RequestedShift
- [ ] Restriction
- [x] Role (has two: ordinary and admin)
- [ ] Shift
- [ ] ShiftPreference
- [ ] ShiftsTask
- [ ] Stat
- [ ] Sticky
- [ ] SubRequest
- [ ] Task
- [ ] Template
- [ ] TemplateTimeSlot
- [ ] TimeSlot
- [x] User
- [x] UserConfig (default created along with user)
- [x] UserProfile
- [x] UserProfileEntry
- [x] UserProfileField

**Comment by orenyk** [comment]
Wow, that's a *ton* of models.

**Comment by mnquintana** [comment]
@njlxyaoxinwei You shouldn't need to worry about `PunchClock` or `PunchClockSet` – Punch Clock is a perennially broken feature that no one uses.

**Comment by njlxyaoxinwei** [comment]
![image](https://cloud.githubusercontent.com/assets/3580898/6074489/a9075baa-ad8d-11e4-9881-fca98f0cdd23.png)
