### ISSUE TITLE
Keyboard shortcut for Mac users

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/shifts#434]
Under the Update the Report function on a shift report, the text says:

`Ctrl+Enter to quickly add to report`.

Perhaps this could be amended to:
`Ctrl+Enter // Command+Enter to quickly add to report`.

Is it possible to detect the user's OS via a ruby app? 

Pull request to (hopefully) follow.

**Comment by jasonkliu** [comment]
I think I have it working, but it's hard to test because the local version can't be tested on multiple OS's easily.  Maybe I'll push it to Heroku?  Still a work in progress.

**Comment by mnquintana** [comment]
Is <kbd>Cmd+Enter</kbd> not working for you? I set that up as a keyboard shortcut for Mac users awhile ago, and it is working on our development instance. Granted, it's not ideal, because on Macs both <kbd>Cmd+Enter</kbd> and <kbd>Ctrl+Enter</kbd> work, but I don't think that's necessarily a bad thing.

**Comment by jasonkliu** [comment]
Ooh, both <kbd>Cmd+Enter</kbd> and <kbd>Ctrl+Enter</kbd> work on Mac. I was unaware that you could use Ctrl shortcut since most applications never use the Ctrl key on Macs.

Tentative solution was detecting the OS of the user in the form and displaying Command instead of Ctrl for Mac users - it seems more like a native application then.  What do you think?
